name = "typst-lsp"
version = "0.11.0"
author = "nvarner"
display-name = "Typst LSP"
description = "A language server for Typst"
icon = "icon-typst.png"
respository = "https://github.com/nvarner/typst-lsp/"
wasm = "out/lapce.wasm"

[activation]
language = ["typst"]
workspace-contains = ["**/*.typ"]

[config."typst-lsp.serverPath"]
default = ""
description = "The extension can use a local typst-lsp executable instead of the one bundled with the extension. This setting controls the path to the executable."
